apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ac-app
    spec:
      containers:
        - name: ac-app-container
          image: <DOCKERHUB_USERNAME>/ac-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"