apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ac-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ac-app-deployment
  minReplicas: 1
  maxReplicas: 5